### ISSUE TITLE
Error:Could not find eu.davidea:grabver:0.2.0.

### ISSUE THREAD

**Issue by royhenengel** [davideas/AndroidStarterApp#1]
Hi David, how are you?
I saw this project of yours in your "flexible adapter" repository, and couldn't wait to see what you came up with.
When opening the repository in android studio, I get an error:

> Error:Could not find eu.davidea:grabver:0.2.0.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/eu/davidea/grabver/0.2.0/grabver-0.2.0.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/eu/davidea/grabver/0.2.0/grabver-0.2.0.jar
    https://jcenter.bintray.com/eu/davidea/grabver/0.2.0/grabver-0.2.0.pom
    https://jcenter.bintray.com/eu/davidea/grabver/0.2.0/grabver-0.2.0.jar
    file:/Users/chenengel/.m2/repository/eu/davidea/grabver/0.2.0/grabver-0.2.0.pom
    file:/Users/chenengel/.m2/repository/eu/davidea/grabver/0.2.0/grabver-0.2.0.jar
Required by:
    project 

hoping to hear from you soon so I can start exploring the project.

**Comment by davideas** [comment]
@henengel, sorry about that error, indeed that GrabVer library is not ready yet.
And the 2 projects are embryonic, still a bit of patience.

**Comment by royhenengel** [comment]
@davideas 
Lol no problem... :) (General suggestion, in my opinion, only, it's best to publish once it's ready don't you think? )
Another suggestion if I may, because I'm relatively a new dev, I have been experiencing a lot and as part of my learning experience, I wrote some helper classes (like you did in your new project). Currently, I wrote a Facebook helper class to handle all related Facebook and Google account things.
If you are intrested, you can include them in your project.
The code may need some small revision, and I would love to participate, share and of course if you don't mind and it is possible, learn from an experienced dev like yourself.
Feel free to accept of decline, either is OK.
Looking forward to hearing from you...

**Comment by davideas** [comment]
I appreciate your suggestion for the helper classes, @henengel.
The current status of this project is really at the beginning stage as already said. GrabVer is now working, but I need to publish it so everybody can simply import it instead of generating the jar locally. A part this, the app can be built by commenting the GrabVer plugin.

My plan is to start from Settings.

**Comment by royhenengel** [comment]
@davideas 
1. **GarbVer** - OK thank you.
2. **The helper classed I mentioned earlier** -  didn't get if you are interested in integrating my helper classes... I would love to help as much as possible and get you professional feedback.

**Comment by davideas** [comment]
@henengel, yes let's see what have you done.

**Comment by royhenengel** [comment]
@davideas 
Great!!!
Still, have final touches to implement.
I'll finish everything in the next few days...
How would you have me send you everything?
Would you like to add me as a collaborator? Fork the project and send a pull request? Any other way?

**Comment by royhenengel** [comment]
@davideas 
Also, If I have a question of implementing something, I would love to be able to ask you in short how to do it the right way and save you the need to revise the code later on... what is the easiest way for you to communicate? Email? Another way?

**Comment by davideas** [comment]
@henengel, email is ok.
I will add you as collaborator, I think it is simpler.

As for GrabVer, I'm creating a script for publishing it.

**Comment by royhenengel** [comment]
@davideas 
What is your email to communicate outside of here?

**Comment by davideas** [comment]
@henengel, I added again it in my profile, i thought it was already visible.
